### ISSUE TITLE
Not working CORS

### ISSUE THREAD

**Issue by barshag** [MiscellaneousStuff/meta-sam-demo#1]
when I try to run it loccally

Got also these messages:

HY IS THIS NOT RUNNING? bundle.js:112:11
PRE-INIT MODEL? bundle.js:114:13
INIT MODEL? bundle.js:116:15
INSIDE TRY OF INIT MODEL?

**Comment by MiscellaneousStuff** [comment]
Could you explain what CORS errors you are getting? Because I do remember also getting them at the start but I thought this had been resolved.
