### ISSUE TITLE
The project starts but cannot be used normally

### ISSUE THREAD

**Issue by zwfun** [MiscellaneousStuff/meta-sam-demo#10]
![image](https://github.com/MiscellaneousStuff/meta-sam-demo/assets/9522995/a568c80d-9ac8-4c3e-856b-0da95bf1ee9b)

**Comment by zwfun** [comment]
![image](https://github.com/MiscellaneousStuff/meta-sam-demo/assets/9522995/a45ee58f-c329-4d55-8e98-678417ce5b24)

**Comment by ericsvendsen** [comment]
I'm trying to take pieces of this project and make my own app. The "original" version of the repo that I cloned a few weeks ago works just fine. My new app kept throwing the same errors you're seeing.

After a lot of googling, cursing, and entreaties to a higher power, I suddenly came upon the realization that the versions for `onnxruntime-common` and `onnxruntime-web` are different between my 2 projects. I changed my new app to `1.14.0` specifically for both dependencies, and boom, it works. I don't know what changed between the versions - there is nothing specific on the onnx releases page that I can see. At this point though, I'm going to count this as a win and move on.
```
"onnxruntime-common": "1.14.0",
"onnxruntime-web": "1.14.0",
```
Good luck....

**Comment by ericsvendsen** [comment]
Finally found out the true cause of this problem. Each release of `onnxruntime-web` uses version-specific `wasm` files. So when a new version is released, you have to use the assets released with that version.

I just set up an npm script to copy the relevant files from `node_modules` to my `public` folder whenever I start or build the project so I won't run into this problem every time the package gets updated.
