### ISSUE TITLE
How do you return the data when you call these two interfaces? I want to transfer through a local backend service?

### ISSUE THREAD

**Issue by liujiadong369** [MiscellaneousStuff/meta-sam-demo#17]
const API_ENDPOINT          = "https://model-zoo.metademolab.com/predictions/segment_everything_box_model";
const ALL_MASK_API_ENDPOINT = "https://model-zoo.metademolab.com/predictions/automatic_masks";

How can I tweak my backend code to implement these two interfaces?
Thank you very much!

**Comment by MiscellaneousStuff** [comment]
Look at [this](https://github.com/MiscellaneousStuff/meta-sam-demo/issues/5) discussion for a better explanation.

Alternatively, [this](https://github.com/haibingtown/segment-matting) project which is extended from this project explicitly does what you want. The extended project is based on explanations from the above.
