### ISSUE TITLE
How to set up a debugger on this project?

### ISSUE THREAD

**Issue by avi-raj1** [MiscellaneousStuff/meta-sam-demo#18]
I have tried several things and nothing seems to be working. All I want is to setup break-points using visual studio code. Is this project debug friendly? If not, what are the additional changes required to debug this project?

**Comment by MiscellaneousStuff** [comment]
[This](https://code.visualstudio.com/docs/typescript/typescript-debugging) documentation should be able to help you more than any specific advice I can give. There is nothing in this project specifically which should be making debugging harder.
