### ISSUE TITLE
Cool project. How to save the segmentation mask?

### ISSUE THREAD

**Issue by askerlee** [MiscellaneousStuff/meta-sam-demo#19]
Suppose I segment an object and want to save a 1/0 mask to indicate its location in the image. Seems this function is not implemented yet? Would highly appreciate if it could be done 😄

**Comment by MiscellaneousStuff** [comment]
The functionality has been implemented, just not documented anywhere :P.

If you refer to [this](https://github.com/MEng-Team-Project/MEng-Team-Project-Web/blob/main/client/src/views/Main/components/SegmentModal/components/Stage.js) example implementation, it shows how you can setup a custom `<Stage />` component with this project running as an iFrame. Then the host `<Stage />` component will interace with the `meta-sam-demo` page using [this](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage) API. It is the easiest way to segregate this page and access the masks. It currently returns the SVG co-ordinates but there should be code in their to convert it to whatever format you need.

**Comment by askerlee** [comment]
Thank you!
