### ISSUE TITLE
Can´t run build

### ISSUE THREAD

**Issue by rebotnix** [MiscellaneousStuff/meta-sam-demo#3]
npm run build

> meta-sam-rip@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

[eslint] node.params is not iterable
Occurred while linting /Users/**createContext.tsx:1
Rule: "@typescript-eslint/no-unused-vars"

Anyone had the same issue?

I´m using nodejs 18.12.1.

Thanks.

**Comment by MiscellaneousStuff** [comment]
I've ran your build command and ran into the same issue as well, will look into this.

**Comment by MiscellaneousStuff** [comment]
Ok this should be fixed now, the only problem is that the linter is quite strict but if you copy the latest version, `npm run build` works 100% now!
