### ISSUE TITLE
Failed to compile when npm run start

### ISSUE THREAD

**Issue by lurenlym** [MiscellaneousStuff/meta-sam-demo#7]
I am newer to npm. When I want to npm run start, it outputs error

![image](https://user-images.githubusercontent.com/26338549/231059060-0d0f87d5-accd-4b69-92d7-8e8afa46c999.png)

node version: v18.15.0
npm version: 9.5.0

It seems some webpack version errors:

![image](https://user-images.githubusercontent.com/26338549/231059638-d3e45df5-e544-440d-a169-46ccadc5ef46.png)

Add SKIP_PREFLIGHT_CHECK=true to an .env file can ignore this issue

**Comment by ZhengPeng7** [comment]
You don't need to make the .env file. That's the problem of the webpack: https://stackoverflow.com/questions/63655361/get-a-different-version-of-webpack-was-detected-higher-up-in-the-tree-error-i.

**Comment by lurenlym** [comment]
> You don't need to make the .env file. That's the problem of the webpack: https://stackoverflow.com/questions/63655361/get-a-different-version-of-webpack-was-detected-higher-up-in-the-tree-error-i.

Thanks， I clean the npm cache and re-install. The webpack version confit has soled. Now the error as follow:
![image](https://user-images.githubusercontent.com/26338549/231159473-d25f6d14-cee7-4e90-b12d-cff40599f366.png)

**Comment by Callidior** [comment]
I had the same issue. It looks like Node.js v18.15 is not recent enough for the used webpack version.
I solved it by upgrading Node.js to the most recent v19.9.
