### ISSUE TITLE
I used the official code to transfer pth model to onnx model, which cannot be used in this project

### ISSUE THREAD

**Issue by sun631998316** [MiscellaneousStuff/meta-sam-demo#9]
How to modify the code of export onnx model? I used the official code to transfer pth model to onnx model, https://github.com/facebookresearch/segment-anything/blob/main/scripts/export_onnx_model.py; which cannot be used in this project.  Could you please provide the code of export onnx model?

**Comment by haibingtown** [comment]
Take a look at this project, here we introduce how to export onnx model

https://github.com/haibingtown/segment-matting
